Burn tokens to reclaim buffers (#188)
Modify the `ReclaimBuffer` instruction so that dust tokens in buffers
don't prevent a buffer from being reclaimed.

Note that it's still possible that a buffer can't be reclaimed, for
example in the case of a frozen token.
However, this should cover the most common realistic scenario where
buffer rent is locked.

This is done by having the caller specify in the instruction a limit for
the tokens to burn.
Realistic scenarios:
- If it's 0, nothing is burned, which I recommend as the default since
we probably usually prefer to sell the tokens.
- If we don't find a way to sell, we should probably specify the exact
balance we want to burn. This is to prevent issues where we burn more
than expected if the balance changes in the meantime (which is an
indication of a bug somewhere else).
- If the balance is constantly changing, we can just use max u64 to burn
whatever's there.

I also implemented some fancy revert logic after some discussion with
@kaze-cow.
The reclaim reverts if _all_ reclaim operations revert. If even one
succeeds, it passes.
This is for two reasons:
- If we're batching multiple reclaims in a script, we don't necessarily
want it to fail if by chance one of the buffers change its balance in
the meantime.
- However, we want to avoid the case where a script bugs out and just
tries to reclaim the same buffer over and over, not realizing that the
transaction itself isn't working. This is something that happened to us
in the past with ETH flow order reclamation, which lead to unnecessary
draining of funds, This case will be eventually caught by the "don't
allow all of them to fail" mode.

Exception: if the burning succeeds but the reclamation fails. This is
probably a sign of something going wrong, and we don't want to burn
money if the buffer isn't cleared, so we just revert the whole batch.

## How to test

New and updated tests.

---------

Co-authored-by: Kaze <230549489+kaze-cow@users.noreply.github.com>